rele/client.py

Don't provide credentials when PUBSUB_EMULATOR_HOST is set in the environment.
So we can use the Google Pub/Sub emulator

Respect PUBSUB_EMULATOR_HOST env var

---

rele/subscription.py

Add docstrings to the sub decorator to get documentation started. 
Just getting started with documenting how the rele package works. 
Is this how we want our docstrings styled?

Add docstrings to the sub decorator

---

rele/client.py
rele/subscription.py
tests/test_subscription.py

Parse  `b''` as `None`
It cannot be deserialized as JSON.

Parse as None an empty message

---

rele/client.py
rele/subscription.py
tests/test_client.py
tests/test_subscription.py

Use json.dumps with drf's encoder, not the whole renderer.
It was simply incorrect. For example `.render(None)` was an empty string, which is not valid JSON.

Use drf jsonencoder, not renderer

---

CHANGELOG.md

Serve github pages off `docs/` dir.

Setup github pages to work off docs/

---

Makefile
rele/subscription.py

* Fix warning converting docstring for **kwargs
* Add task `make install-dev-requirements` to install all dependencies for development
* Remove warning when generating the html documentation
* To run just one command to install all necessary dependencies for development

Add task to install development dependencies

---

.readthedocs.yml
docs/Makefile
docs/conf.py

Configuration to use readthedocs.
As the idea of using GitHub Pages for docs didn't work as expected we can give it a try to ReadTheDocs.

Changes to use readthedocs

---

README.md
rele/management/commands/runrele.py
rele/subscription.py
tests/settings.py
tests/test_subscription.py
tests/test_worker.py

Use custom value as prefix to any subscription instead of static project name.
Small iteration in order to remove completely Django settings usage.

Subscriber prefix param

---

docs/index.rst
docs/modules/client.rst
rele/client.py
rele/subscription.py
tests/conftest.py
tests/test_client.py
tests/test_subscription.py

* Add optional parameter published_at  to publish function, it uses `time.time()` in case published_at is None.
* client.Publisher documentation page.
It can be useful to have the time that the message was published.

Add timestamp to published message

---

docs/index.rst
docs/modules/publish.rst
docs/modules/subscription.rst
docs/modules/worker.rst

I've created a modules directory inside the docs folder for a better structure of our documentation.
Now client, publish, subscription and worker template are inside docs/modules.
As we start to increase or documentation it can be hard to find files. If we split them into directories is much easier to find and organise them.

Move all documentation modules templates from docs to docs/modules

---

rele/client.py
tests/conftest.py
tests/test_client.py

Add `DEFAULT_ACK_DEADLINE` variable to configure the default ack deadline (thus, overriding the default value set by Google). Plus, the `create_subscription` method in `Subscriber` class also accepts a custom ack deadline value.
The default value of 10 seconds set by Google may not be suitable in most of our use cases. Closes #44.

Parametrize subscription ack deadline

---

Makefile
README.md

Use coverage to run tests for codecov. 
Add the codecov badge in the readme.
This increases our codecov from 58% to ~80%. The previous implementation used pytest directly which skewed the results of the coverage report. For instance, [it did not mark our import statements in the modules as covered](https://codecov.io/gh/mercadona/rele/src/modify-ack-deadline/rele/client.py#L2), even though they were. 
It'll be a reminder that we need to increase the coverage.
#46

Increase Codecov from 54% to 83%

---

setup.py

Register `rele.contrib` package in `setup.py`.
This way the package gets shipped with the library.

Register contrib package in setup.py

---

rele/__init__.py
rele/apps.py
rele/config.py
rele/contrib/logging_middleware.py
rele/management/commands/runrele.py
rele/middleware.py
rele/publishing.py
rele/worker.py
tests/conftest.py
tests/settings.py
tests/test_publishing.py
tests/test_subscription.py
tests/test_worker.py

Move config to an Object. 
Call rele.setup in apps.py
Moves dependency of django.conf.settings away from the Middleware and makes config more agnostic, less django dependent.
Addresses #38

Decouple django settings

---

README.md
setup.py

Use `find_packages` from setup tools
```
>>> find_packages(exclude=("tests",))
['rele', 'rele.management', 'rele.contrib', 'rele.management.commands']
```
To avoid #61 
Fixes the issue discovered in #61

Use find_packages in setup.py

---

Makefile
rele/subscription.py
tests/test_subscription.py

Add a new parameter called `filter_by` to the `sub` decorator that filters the messages to be processed. The filtering is based on the message attributes.
There are messages sent to a subscription that shouldn't be processed.
Refs #35

Filter by message attributes

---

docs/quickstart/rele_and_emulator.rst

- Reflect new relé settings in a Django project
- Add settings import in code snippet
Documentation doesn't reflect the current status of relé and needed to be updated.

Update quickstart documentation

---

CHANGELOG.md
rele/__init__.py
runtests.py

Ability to use just rele in the APPS of django settings.
Without this we need to specify `rele.apps.ReleConfig`.

Add possibility to use rele in django apps

---

CHANGELOG.md
rele/__init__.py

Bump rele version with default filters and default app config.
Fix problems with rele on django settings

Bump verion with default filter and defalut app config

---

AUTHORS.md
CONTRIBUTING.md

Add authors file to the repo
Give credit where credit is due.

Add Authors file with the current contributors

---

rele/client.py
tests/test_client.py
tests/test_subscription.py

Allow the Publisher class to have a configurable json encoder.
One small step for making the library django dependency free. 
Addresses #8

Json encoder class is configurable in the Publisher client Class

---

README.md
docs/api/settings.rst
rele/client.py
rele/config.py
rele/publishing.py
tests/conftest.py
tests/test_client.py
tests/test_config.py

Add the `ENCODER` setting to the config object.
It allows the global publisher to be initialized with the desired encoder. 
Addresses #8

ENCODER settings config

---

docs/api/settings.rst
rele/client.py
rele/config.py
rele/management/commands/runrele.py
rele/management/commands/showsubscriptions.py
rele/worker.py
tests/commands/test_runrele.py
tests/conftest.py
tests/test_client.py
tests/test_worker.py

In attempt to consolidate all the rele settings out there into one rele dict setting object, here is the moving of the configuration for the default ack_deadline. 
Fix #83

Move default ack deadline to the rele config dict

---

rele/client.py
requirements/base.txt
setup.py
tests/test_config.py

Remove DRF as a project dependency. This is a breaking change.
Make the project less dependent on django related projects.
#90

Remove drf as a dependency

---

docs/guides/basics.rst

Write 'Message attributes' section.
Missing explanation regarding `published_at` attribute set before publishing a message.
This attribute is very helpful to solve message order problems, for example, when the messages are received in a different order that were sent.

Write 'Message attributes' section

---

AUTHORS.md
docs/api/settings.rst
rele/contrib/logging_middleware.py
rele/middleware.py
rele/subscription.py
tests/test_subscription.py

Added the subscription message as a parameter for some middleware hooks:
```python
pre_process_message
post_process_message_success
post_process_message_failure
``` 
In the case of `post_process_message_failure`, the message was also added as an extra in the `LoggingMiddleware`
Clients might want to log the message in middlewares, and right now, as it is not received in the hooks.
Fix #98

Add message as a parameter for middleware hooks

---

rele/management/commands/runrele.py
requirements/test.txt
setup.cfg
tests/commands/test_runrele.py
tests/settings.py

Warn the user starting the Relé worker when running `python manage.py runrele` when the database `CONN_MAX_AGE` is not set to 0.
This can be a severe oversight when setting up Relé leading to the database connections being exhausted. 
Addresses #94

Check max conn age setting and warn when not 0

---

rele/contrib/__init__.py

Test Django Middleware from `__init__.py`
When using Relé as standalone, the import from `__init__.py` occurs when registering the middleware. This in turn loads that module which has a Django reference. This reference when standalone does not exist. 
As such, one approach is to test the existence of Django, and then import it.

Safely install Django middleware from __init__.py

---

docs/api/settings.rst
docs/guides/basics.rst
docs/guides/django.rst
docs/guides/filters.rst
docs/guides/rele_and_emulator.rst
docs/index.rst
rele/contrib/logging_middleware.py

Add Django and standalone documentation.
Preparing for the 0.7.0 release which remove django as a requirement
#104

Split django specific docs and standalone docs

---

README.md

Update the readme
We should point to the docs for a quickstart. And also include the install directions.

Update readme to include the quickstart in the guide

---

.travis.yml
setup.py

Add python 3.8 to travis.
[It was officially released on Oct 14, 2019](https://www.python.org/downloads/release/python-380/)
This would allow us to officially add Python 3.8. However, it seems that grpcio is not compiled for Python 3.8 and therefore the [travis build takes much longer to complete.](https://travis-ci.org/mercadona/rele/jobs/601163949). Ran for 5 min 40 sec. 
So either we can wait and not support 3.8 yet, or merge this and have the travis build take longer than expected. 
I leave it as a draft until we decide.

Add python 3.8 to travis

---

rele/worker.py

Added missing calls to documented hooks
I was checking out all the middleware hooks and noticed these two were not called. I'm not actually using these hooks so I'm not sure they are necessary but they are mentioned in the docs and implemented in the MiddlwareBase class.

Add missing worker middleware hooks

---

rele/config.py
rele/middleware.py

Add kwargs to the setup method and pass them through to the BaseMiddleware setup function
Allows users to configure custom configuration for Middleware.
Possible fix for #120

Add kwargs to setup method passed through to middleware

---

docs/guides/basics.rst
rele/management/commands/runrele.py
rele/worker.py
tests/commands/test_runrele.py
tests/test_worker.py

Add a shortcut method for calling setup, start, and sleep. 
Make it easier to start a worker.
#114

Worker run method

---

CHANGELOG.md
rele/__init__.py
rele/management/commands/runrele.py
tests/commands/test_runrele.py

When `runrele` is executed with version `0.8.0`, we received:
```
Traceback (most recent call last):
File "manage.py", line 15, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
output = self.handle(*args, **options)
File …
```

Fix runrele command

---

AUTHORS.md
rele/contrib/__init__.py
rele/contrib/flask_middleware.py
rele/contrib/logging_middleware.py
tests/test_middleware.py

Adds middleware for easy integration with Flask and fixes issue with logging Middleware not expecting kwargs.

Rele flask

---

rele/contrib/logging_middleware.py
tests/test_subscription.py

Add message `attributes` property to log metrics object.
Filter log messages by custom message attribute. It is possible than a topic has several subscriptions which filter messages by custom message attribute like `country_code`. Then, it would be nice to filter log messages by same message attribute.
Fixes #113

Add message attributes to metrics log

---

docs/api/settings.rst
rele/client.py
rele/config.py
rele/publishing.py
tests/conftest.py
tests/test_client.py
tests/test_publishing.py
tests/test_subscription.py

Configurable timeout while waiting for a successful result from the pubsub future. https://googleapis.dev/python/pubsub/1.1.0/publisher/api/futures.html?highlight=result#google.cloud.pubsub_v1.publisher.futures.Future.result
We would like to control the timeout for publishing.
Addresses #136

Add publishing timeout

---

docs/api/settings.rst
rele/client.py
rele/config.py
rele/management/commands/runrele.py
rele/subscription.py
rele/worker.py
tests/commands/test_runrele.py
tests/test_worker.py

Add custom ThreadPoolExecutor to each subscriber. It follows the pattern shown [ here.](https://googleapis.dev/python/pubsub/latest/_modules/google/cloud/pubsub_v1/subscriber/scheduler.html#ThreadScheduler) 
And also allows customer thread count per subscription. 
Note: Ill leave this as a draft since I strongly believe that code coverage can be increased. If this is the direction we want to go, then Ill add it. 
We want to be able to control the number of thread per subscription. 
Addresses #135

Add subscription ThreadPoolExecutor

---

rele/client.py
rele/config.py
rele/worker.py
tests/test_config.py
tests/test_worker.py

This relates to #114 & #119
This makes makes all config variables nullable falling back to standard
google envars, without breaking the current api.
The new apis would look like this is you have
`GOOGLE_APPLICATION_CREDENTIALS` set.
```
rele.config.setup()
```
```
w = Worker([sub1, sub2])
w.run_forever()
```
TBH, I think reading global configs from the environment is easier to
reason about than a singleton so I'd suggest that. Any non globals should
just be passed into the instances on __init__.
Provide a description of what has been implemented.
Give an explanation of why.

Clean up rele.config.setup + Worker() init

---

CHANGELOG.md
docs/guides/flask.rst
docs/index.rst
rele/__init__.py

Bump version to 0.9.0
Register flask documentation and fix formatting
Release 0.9.0

Bump version to 0.9.0

---

rele/subscription.py
tests/test_subscription.py

Catch `JSONDecode` errors and ack messages.
There is no possibility of processing such messages successfully so they have to be discarded.
Fix #140

Ack messages when data not json serializable

---

rele/worker.py
tests/test_worker.py

ThreadScheduler should be passed into the `consume` api which uses the `subscribe` api of the [google pubsub lib](https://googleapis.dev/python/pubsub/1.0.2/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.subscribe)
Breaks 0.9.0
Fixes #144

Use ThreadScheduler instead of ThreadPoolExecutor

---

rele/client.py
tests/test_client.py

Catch google.api_core.exceptions.NotFound exception
Worker should not crash if the topic does not exist. 
Fix #133

Dont crash when subscription topic does not exist

---

rele/config.py
rele/subscription.py
tests/test_subscription.py

Modify subscription constructor to allow iterables in `filter_by` and apply all filters.
Current version only allows one filter.
Solver #134

 Allow multiple filters

---

docs/guides/unrecoverable_middleware.rst
docs/index.rst
rele/contrib/unrecoverable_middleware.py

This is useful if you know you will never be able to handle the message
and don't have a dead-letter queue setup.
A custom exception and middleware to automate and ignore bad messages.
I've been using this a fair amount in some of our services and thought it may be useful to others.

Add unrecoverable_middleware

---

docs/api/settings.rst
rele/config.py
tests/commands/test_runrele.py

Change [THREADS_PER_SUBSCRIPTION](https://mercadonarele.readthedocs.io/en/latest/api/settings.html#threads-per-subscription) to 2.
Default thread count is quite high for each subscriber at 10. It would be sensible to opt-in to a higher thread count if necessary.

Adjust default THREADS_PER_SUBSCRIPTION

---

tests/settings.py
tests/test_subscription.py

[Fix tests that break](https://travis-ci.org/mercadona/rele/builds/645982132) because of missing argument "request_queue" argument that was dispalced by delivery_attempt argument
https://github.com/googleapis/python-pubsub/commit/a0937c13107b92271913de579b60f24b2aaac177#diff-9d37cc3aaac018e0c394df450a873e66

Add missing parameter to Message fixture

---

docs/guides/unrecoverable_middleware.rst
rele/contrib/__init__.py

Add the missing class export line to `rele/contrib/__init__.py` to make it possible to import middleware in config. Also, fix docs.
It's not working right now 😿 
---
I wasn't really sure how to write a test for it, but if you give me some pointers I'm happy to give it a go!

🐛 Fix UnrecoverableMiddleWare export and docs

---

Dockerfile
Makefile

I set up a Dockerfile and commands in Makefile to make it possible to run all tests with a single command and no installation required (if you already have Docker).
I really detest installing tons of development environments on my laptop, so set this up for myself, but thought why not share.
But in general, spinning things up in a Docker container greatly lowers the barrier to entry for casual contribution.

🐳 Add Dockerfile and commands in Makefile

---

AUTHORS.md
docs/guides/basics.rst
rele/client.py

Document that only strings are allowed when passing additional parameters to the publish method
This should be documented
Fix #106

Document attribute type limitations when publishing

---

README.md
docs/api/settings.rst
docs/guides/basics.rst
rele/config.py
rele/discover.py
rele/subscription.py
tests/test_publishing.py

- Documentation of the cli on the basics section
- Also some linting on unused imports
- Change the debug log in the autodiscover to info
Its no longer necessary to write your own worker.
#160

Rewrite Basic's docs to cover the CLI

---

docs/guides/basics.rst
rele/__main__.py
rele/discover.py
tests/subs.py
tests/test_discover.py

Add the `--settings` path argument to the cli
Ive noticed different ways of configuring a project. Some with the settings in the root of the project and some projects with a settings file one level deep. This way, we can specify it anywhere and also avoid the possibility of 2 settings files in a project. 
#160 
```
$ rele-cli run --help                  
usage: Relé run [-h] [--settings SETTINGS]
optional arguments:
-h, --help            show this help message and exit
--settings SETTINGS, -s SETTINGS
Settings file dot path. Ex. project.settings. If none
is supplied, Relé will attempt to autodiscover in the
root path.
```
```
$ rele-cli run --settings test.settings
* Discovered subs module: 'test.subs'
* Discovered settings: 'test.settings'
Configuring worker with 1 subscription(s)... …
```

Add settings path to the cli

---

CHANGELOG.md
docs/conf.py
rele/__init__.py
setup.cfg

Bump to version 0.12.0
Add correct path to the docs/conf.py file.
Dont lint the docs directory
When isorting, [the conf.py in docs was linted.](https://github.com/mercadona/rele/pull/164/files#diff-85987f48f1258d9ee486e3191495582dR16) This broke the import path.
```
File "/home/docs/checkouts/readthedocs.org/user_builds/mercadonarele/checkouts/latest/docs/conf.py", line 16, in <module>
import rele
ModuleNotFoundError: No module named 'rele'
```
#164

Bump 0.12.0

---

docs/guides/basics.rst
rele/discover.py
tests/more_subs/subs.py
tests/test_discover.py

Traversal of all packages in a Python path and get the path of the `subs.py` file. 
This way we can have a `subs.py` n-levels deep, and autodiscover it. 
Enhancement of #160 
Here it is working on a local project I have set up.
```
$ rele-cli run --settings test.settings
* Discovered subs module: 'test.subs'
* Discovered subs module: 'test.foo.bar.subs'
* Discovered settings: 'test.settings'
Configuring worker with 2 subscription(s)...
test-delivery-driver-created - some_sub
test-another-topic - some_sub
Cannot subscribe to a topic that does not exist.
```

Traverse all packages for subs.py files

---

README.md
docs/api/settings.rst
docs/index.rst
rele/config.py
requirements/base.txt
setup.py
tests/conftest.py
tests/dummy-pub-sub-credentials.json
tests/test_config.py
tests/test_worker.py

Allow settings with credentials path
Its easier to specify the path of the service account credentials file than it is to make the user instantiate their own credentials object.

GC_CREDENTIALS_PATH setting option

---

CHANGELOG.md
rele/config.py
tests/test_config.py

Deprecate `GC_CREDENTIALS`
It will be removed in 1.0.0

Deprecate GC_CREDENTIALS

---

docs/api/settings.rst
docs/guides/basics.rst
docs/guides/django.rst
docs/guides/emulator.rst
docs/guides/flask.rst
docs/guides/unrecoverable_middleware.rst
rele/config.py
tests/conftest.py
tests/settings.py
tests/test_config.py
tests/test_middleware.py
tests/test_worker.py

Remove deprecated GC_CREDENTIALS setting
It was deprecated in #173 and is scheduled for removal by 1.0.0
#173 #170

Remove GC_CREDENTIALS

---

rele/client.py
rele/contrib/logging_middleware.py
rele/middleware.py
tests/conftest.py
tests/test_client.py

Catch `TimeoutError` when publishing while `blocking` and run `post_publish_failure` hook. Also added `raise_exception` parameter.
Google can raise this error when publishing so it should be handled
#159

Catch TimeoutError and run post_publish_failure when blocking

---

docs/reference.rst
docs/settings.rst
rele/client.py
rele/config.py
rele/worker.py
tests/commands/test_runrele.py
tests/conftest.py
tests/test_client.py
tests/test_config.py
tests/test_worker.py

Deprecate GC_PROJECT_ID. I was even thinking about removing it. Since we can fallback to using the credentials, the removal shouldnt be a breaking change. What do you all think? 
Simpler setup or a user. Less settings == less hassle
#176

Deprecate GC_PROJECT_ID setting

---

CHANGELOG.rst
rele/__init__.py

Bump version to 0.14.0
We have quite a number of things to be deployed before 1.0.0 
#175

0.14.0 release

---

rele/config.py
tests/test_config.py

Raise error when the config loads a repeated subscription
The issue describes it well:
https://github.com/mercadona/rele/issues/180
Fix #180

Fix #180: Raise error when the config loads a repeated subscription

---

rele/publishing.py
tests/test_publishing.py

Implement discovering and setup of settings when publishing without calling to `config.setup()`
To avoid the boilerplate in simple setups.
Fix #177

Discover and load settings when publishing

---

rele/client.py
rele/middleware.py
tests/test_middleware.py

Added new post_publish_hook and deprecate the old one
To have a more consistent interface as suggested in https://github.com/mercadona/rele/issues/181
Fix #181

Add new post_publish_hook and deprecate the old one

---

.travis.yml

Support a Python 3.9 variant
Travis does not yet have Python 3.9 stable as an option in the build. 
We want to be as up to date as possible

Support Python 3.9-dev

---

rele/subscription.py
tests/test_subscription.py

Add validations to the sub decorator. 
Validate the signature of the subscription function to check if it has the correct number of arguments.
Validate the `filter_by` parameter to check if it is a callable or a iterable of callables as defined in the docstring.
Log a warning if the subscription function it's outside a discoverable module to alert the user that that susbcription will not be created.
Improvements suggested in https://github.com/mercadona/rele/issues/186
The use of the `wraps` decorator in the sub decorator is not useful as the decorator returns a Subscription instance and not a function so the expected behaviour of keep the `__name__` and `__doc__` is lost. If someone knows the way to acomplish it please leave a comment.
Fix #186

Add validations to the sub decorator

---

.travis.yml
rele/__init__.py
rele/subscription.py
setup.cfg
setup.py
tests/commands/test_showsubscriptions.py

Stop defining a `default_app_config` for Django.
It's been [deprecated in Django 3.2](https://docs.djangoproject.com/en/3.2/ref/applications/#for-application-authors)

Do not define default_app_config, it's deprecated

---

docs/conf.py
rele/middleware.py

This silences the post_publish warning in the case where you do not implement it
No need to raise a warning for something a middleware author has not done!

Do not implement deprecated middlewares in the base class

---

rele/client.py
rele/contrib/logging_middleware.py
rele/middleware.py
tests/test_client.py

- Log post publish success
- Log pre publish at debug level to not be too noisy
It's more clear to log on success or failure after publishing a message. The existing pre publish may be misleading if the process doing the publishing is killed.
Fix #201

Log post publish success

---

rele/client.py
tests/test_client.py

Automatic topic creation when topic does not exist in PubSub.
When we trying to subscribe to a topic that doesn't exist, there is a crash. In this feature, we create the topic automatically if this does not exist and then retry to initialize the subscription.
PubSub credentials must have editor role.
None

Automatic topic creation

---

docs/settings.rst

Added filter_subs_by setting in documentation
It was not in the _rele_ documentation

Added filter_subs_by setting in documentation

---

rele/client.py
tests/test_client.py

On [Sentry](https://sentry.prod.monline/mdona-production/delivery-api/issues/14651) register `TimeoutError` only changes the exception to catch 
```
from google.cloud.pubsub_v1.exceptions import TimeoutError
from google.cloud.pubsub_v1.publisher.exceptions import TimeoutError
```
If check [Sentry](https://sentry.prod.monline/mdona-production/delivery-api/issues/14651) the exception does not capture and does not execute correctly the exception code. This TimeoutError throws exception from `publisher`.
```
try:
future.result(timeout=timeout or self._timeout)
except TimeoutError as e:
...
```
[Sentry](https://sentry.prod.monline/mdona-production/delivery-api/issues/14651)

[CHANGED] TimeotError from publisher

---

CHANGELOG.rst
rele/__init__.py

Prepare 1.2.0 release
We have some `path` changes and `minor` behavioural changes ready for the bump.
#204 #206 #208 #212

Bump version 1.2.0

---

rele/contrib/__init__.py
rele/contrib/verbose_logging_middleware.py
tests/conftest.py
tests/contrib/test_verbose_logging_middleware.py

Added a `VerboseLoggingMiddleware` that mimics the output format of the current `LoggingMiddleware` but does not truncate the message payload on the post_process and pre_publish failure hooks.
The current `LoggingMiddleware` relies on the `__repr__()` method of the google pubsub message, which truncates the message payload. This, in turn, means that any message payload log will have that payload truncated.
The `VerboseLoggingMiddleware` implementation proposed in this PR adheres to the exact same behavior and formatting of the existing `LoggingMiddleware`, but enabling non-truncated message payload logs.

[Added] Added a Logging Middleware that does not truncate mesage payload.

---

AUTHORS.md
CHANGELOG.rst
rele/__init__.py

Bumped version to v1.4.0 and updated changelog with:
```
1.4.0 (2022-04-13)
-------------------
* [Added] Added a VerboseLoggingMiddleware that does not truncate mesage payload. (#218)
```

Prepare for release v1.4.0

---

.gitignore
CHANGELOG.rst
rele/__init__.py
rele/contrib/verbose_logging_middleware.py
tests/contrib/test_verbose_logging_middleware.py

Deleted `post-publish-message-failure` hook on `VerboseLoggingMiddleware`
The deleted change was originally introduced to have a full non-truncated message log on `post_publish_message_failure`. It turns out that the message passed to the middlewares is **not** the same in the case of `post-publish-message-failure` and `post-process-message-failure` hooks.
`post-process-message-failure` hooks receive the message payload in a wrapper with extra attributes, while `post-publish-message-failure` hooks are given the raw payload, which in turn does not need any additional treatment to have a full log.

[Deleted] Delete `post-publish-message-failure` hook on `VerboseLoggingMiddleware`

---

docs/conf.py
docs/guides/filters.rst
rele/client.py
rele/subscription.py
rele/worker.py
tests/test_client.py
tests/test_worker.py

Add filter expressions to subscriptions. 
Filter expressions are applied by pubsub before sending the message to a specific subscriber. It's use is defined [here](https://cloud.google.com/pubsub/docs/filtering#filtering_syntax) and it prevents the messages to be sent and filtered by the workers.
To give support to this pubsub feature.
N/A

Add filter expressions to subscriptions

---

rele/worker.py
tests/test_worker.py

Implement auto restart of the consumption when futures are done or cancelled
In order to auto heal workers when futures are done

[Added] Implement auto restart of the consumption when futures are done or cancelled

---

.github/CODEOWNERS
Dockerfile

Modify Dockerfile to work fine when using make docker commands
When we use docker make commands, we are receiving this error:
We have fixed this file to work fine :)
I also updated the list of code owners.
**The deleted users are due to not having write access to the repository.

[Changed] Modify Dockerfile to work when using make docker commands

---

rele/contrib/logging_middleware.py
tests/contrib/test_logging_middleware.py
tests/contrib/test_verbose_logging_middleware.py
tests/test_subscription.py

Unify `subscription_message` data types using always an `String` 
After call `post_publish_failure` `subscription_message` contains a `dict` with the original data sent
After call `post_process_message_failure()` `subscription_message` contains a `Message` object
So at the end the library publish a `subscription_message` with different data types.

fix(logging): subscription_message type was different

---

docs/settings.rst

Fix link syntax
This link was not rendered correctly due syntax typo

[fix] Links rendering in FILTER_SUBS_BY

---

docs/settings.rst
rele/client.py
rele/config.py
rele/publishing.py
setup.cfg
tests/conftest.py
tests/test_client.py
tests/test_config.py

Allow customization of the default value of the blocking parameter when publishing new messages. By default is `False` for Backward Compatibility preservation.
Adds documentation for this new setting.
As a developer, I may prefer a `blocking=True` by default so I have full quarantine that my messages have been correctly published.
Fix #202

[add] PUBLISHER_BLOCKING setting

---

docs/settings.rst
rele/client.py
rele/config.py
rele/retry_policy.py
rele/subscription.py
rele/worker.py
tests/commands/test_runrele.py
tests/conftest.py
tests/test_client.py
tests/test_retry_policy.py
tests/test_subscription.py
tests/test_worker.py

Add retry policy to the subscriptions (exponential backoff).
This feature allows to configure either a global (per project) retry policy or at subscription level, allowing us leveraging how  we want the subscriptions to behave (retry wise) when worker fails processing a message.
[More info about the feature here](https://cloud.google.com/pubsub/docs/handling-failures).
#222

Add exponential backoff

---

CHANGELOG.rst
rele/__init__.py

Bump to 1.8.0-beta. This version is released to test the retry policy.
#222

Bump to 1.8.0-beta.

---

rele/contrib/logging_middleware.py
tests/contrib/test_logging_middleware.py

Reverts mercadona/rele#239 to promote v1.8.0-beta.

Revert "Use custom encoder in logging middleware"

---

rele/contrib/logging_middleware.py
tests/contrib/test_logging_middleware.py

Use custom encoder in logging middleware
Log fails when non-serializable elements present in payload

Use custom encoder in logging middleware

---

docs/settings.rst
rele/__main__.py
rele/client.py
rele/config.py
rele/worker.py
tests/commands/test_runrele.py
tests/conftest.py
tests/test_client.py
tests/test_worker.py

Implemented setting the gc region to new topics
By default Google Cloud sets it to a random storage location policy

Implemented setting the gc region to new topics

---

rele/__init__.py

Bumped rele version to 1.12.0b1
To be able to detect subscriber on different folder levels.
[Related PR](https://github.com/mercadona/rele/commit/f3ec931adf1f9f7051237f8f77c5b5494c3d0351)

[Changed] Bumped rele version to 1.12.0b1

---

CHANGELOG.rst
rele/__init__.py

Update `rele` to version `1.13.0`
We recently added changes to the `VerboseLoggingMiddleware` and want to publish them in a new version.
https://github.com/mercadona/rele/pull/240

[Added] Bump rele version to `1.13.0`

---

.github/workflows/pr.yml
setup.py

Added Python 3.11 support in the CI as well as updating the metadata in the setup.py file
Python 3.8 is EOL and Python 3.11 has been out for a while now.

Update with Python 3.11 support

---

rele/worker.py
requirements/test.txt
tests/test_worker.py

Add test coverage for alfa version https://github.com/mercadona/rele/pull/267
We want test coverage.
- https://github.com/mercadona/rele/issues/270

Add reconnect test coverage

---

Makefile
rele/__init__.py
rele/worker.py
requirements/test.txt

Terminate the subscriptor process behaviour when connection to Pub/Sub is not reachable.
gRPC library has an open bug that does not manage the reconnection, so if internet connection was lost, it enters in a reconnection infinite loop.
[Add related issue's number. Example: Fix #1](https://github.com/grpc/grpc/issues/20562)

Refactor to replace print by logger.debug

---

rele/__init__.py
rele/client.py
rele/config.py
rele/publishing.py
rele/worker.py
tests/commands/test_runrele.py
tests/conftest.py
tests/test_publisher.py
tests/test_publishing.py
tests/test_subscriber.py
tests/test_worker.py

Added `CLIENT_OPTIONS` settings to provide configurations for the Pub/Sub [publisher](https://cloud.google.com/python/docs/reference/pubsub/latest/google.cloud.pubsub_v1.publisher.client.Client#google_cloud_pubsub_v1_publisher_client_Client_api_endpoint) and [subscriber](https://cloud.google.com/python/docs/reference/pubsub/latest/google.cloud.pubsub_v1.subscriber.client.Client#google_cloud_pubsub_v1_subscriber_client_Client) clients.
```
RELE = {
"CLIENT_OPTIONS": {"api_endpoint": "custom-api.interconnect.example.com"},
}
```
We want to ability to update the global endpoint for publisher and subscriber clients.

Added a setting to provide client options for Pub/Sub clients

---

rele/__init__.py
rele/worker.py
tests/test_worker.py

Updated how we check the internet connection. Previously we were using `www.google.com` to check the internet connection. Since we added the option to provide `api_endpoint` via  CLIENT_OPTIONS settings, we want to use the same endpoint to check the internet connection.
In cases when we are connecting to different endpoint for example (interconnect), we want to check the internet connection using that endpoint.

Check internet connection using api_endpoint if present in CLIENT_OPTIONS settings

---

rele/client.py

According to the documentation topic must be created manually but in reality `rele` is creating the topic automatically.
The feature was added in this #206 but the documentation was not updated.

Updated the topic creation documentation

---

.readthedocs.yml

Added build configurations to fix ReadTheDocs build
ReadTheDocs build is failing because it do not find the build configurations.

Added build configurations to fix ReadTheDocs build

---

rele/__init__.py
setup.py

- Require at least pubsub 2.7.1
Provide a description of what has been implemented.
- In version 2.7.1 https://github.com/googleapis/python-pubsub/releases/tag/v2.7.1 pytz is deprecated, we don't want to have this dependency as a requirement since is not necessary in upper versions.

Require at least pubsub 2.7.1

---

docs/settings.rst
rele/client.py
rele/config.py
tests/commands/test_runrele.py
tests/conftest.py
tests/test_subscriber.py
tests/test_worker.py

Allow creating topics on multiple Google Pub/Sub regions
We want topics to be created on multiple Google Pub/Sub regions to improve reliability and GDPR compliance
#288

Allow create topics on multiple Google Pub/Sub regions

---

rele/subscription.py
tests/test_subscription.py

Perform a nack over the message when an exception is raised
Rele does not perform a nack after an exception when processing a message. This makes the streaming pull manager leaser hold the message for one hour, so pubsub does not retry it until then. As we have now a retry policy configuration, after the exception is handled it should do a `message.nack()` to drop the lease over the message and make pubsub to retry it again.

[Proposal] Perform a nack over the message when an exception is raised

---

rele/subscription.py
tests/test_subscription.py

Reverts mercadona/rele#254
Automatic ack could cause flooding in subscribers if they are not configured with an exponential backoff retry policy.

Revert "[Proposal] Perform a nack over the message when an exception is raised"
