- rele/client.py
- tests/test_client.py
Publishing speeds decrease dramatically when not blocking
> Non-blocking behaviour when publishing by default

- .editorconfig
- .github/CODEOWNERS
- .github/pull_request_template.md
- .gitignore
- Makefile
And .editorconfig to make life easier
> Add code owners and PR template

- rele/client.py
- rele/subscription.py
- tests/test_client.py
- tests/test_subscription.py
Add extra parameters to subscription log
This allows monitoring by prometheus
> Add metrics in subscription log

- rele/subscription.py
- tests/test_subscription.py
Adapt metrics to prometheus
Because is already configured with this parameters
> Adapt metrics to prometheus

- rele/subscription.py
- tests/test_subscription.py
Reestructure log format metrics
It makes easy monitoring the subscriptions
> Reestructure log format metrics

- rele/subscription.py
- tests/test_subscription.py
Add log information in all subscription process
To can scrap the metrics in prometheus
>  Add remaining subscription log

- rele/client.py
- rele/subscription.py
- tests/test_client.py
Change published log format to can scrape this with prometheus
To can use logs in grafana
> Change published log format to can scrape this with prometheus

- docs/Makefile
Try to generate sphinx documentation using make github task 
To generate the documentation automatically
> Add github task to generate html on github

- README.md
Extra pizazz
Because its beautiful and needs to be displayed for everyone's viewing pleasure
> Logo in the Readme

- README.md
Readme link in docs
Makes finding the docs easier
> Add rtd link to readme

- docs/index.rst
- docs/quickstart/rele_and_emulator.rst
Guide how to use rele and pub/sub emulator.
It can be helpful to have a guide like this to help us in development.
> Add tutorial of how to run rele and pub sub emulator

- Makefile
- docs/index.rst
- docs/publish.rst
- docs/worker.rst
- rele/publishing.py
- rele/worker.py
Add some more docs to the project.
Also simplified the makefile
More docs the better
> Publish function docs

- .travis.yml
- Makefile
- requirements/test.txt
Add codecov to the CI pipeline.
Why not?
> Add codecov

- rele/client.py
- rele/subscription.py
- rele/worker.py
Add some internal linking to classes and methods in the docs
Make things linkable in the docs
> Add links to publish docs

- Makefile
- rele/client.py
- rele/contrib/__init__.py
- rele/contrib/logging_middleware.py
- rele/management/commands/runrele.py
- rele/middleware.py
- rele/subscription.py
- rele/worker.py
Fix linting command and linting errors
It was wrong
Fixes #59
> Fix linting command

- CHANGELOG.md
- CONTRIBUTING.md
- rele/__init__.py
Prepare changelog of all major features over the past week
New version 0.4.0
> Prepare changelog and bump version

- .codecov.yml
- .gitignore
Remove codecov comments via the .codecov.yml
Spammy bot
See https://docs.codecov.io/docs/pull-request-comments for more details
> Remove codecov comments

- CHANGELOG.md
- README.md
Fix the quickstart guide in the docs
We had someone who configured their project incorrectly due to outdated docs
> Fix the readme docs about the settings

- .travis.yml
- Makefile
- README.md
- docs/conf.py
- rele/__init__.py
- rele/apps.py
- rele/client.py
- rele/config.py
- rele/contrib/django_db_middleware.py
- rele/contrib/logging_middleware.py
- rele/management/commands/runrele.py
- rele/management/commands/showsubscriptions.py
- rele/management/discover.py
- rele/middleware.py
- rele/publishing.py
- rele/subscription.py
- rele/worker.py
- requirements/test.txt
- runtests.py
- setup.py
- tests/commands/test_runrele.py
- tests/commands/test_showsubscriptions.py
- tests/conftest.py
- tests/settings.py
- tests/test_client.py
- tests/test_config.py
- tests/test_publishing.py
- tests/test_subscription.py
- tests/test_worker.py
Apply black linting. It seems to be mostly single --> double quotes. 
Apply an opinionated formatter as discussed in #65 
#65
> Try out black

- CHANGELOG.md
- rele/__init__.py
- Bump version.
- Add items to changelog
We have some stuff ready to be released
> Prepare 0.5.0 release

- CHANGELOG.md
- docs/guides/basics.rst
- docs/guides/filters.rst
- docs/index.rst
Its the start of a basics guide
To give people who are new, a place to start
> Basics documentation

- Makefile
- rele/client.py
- More documentation for the subscriber client
- add clean tests for removing the pytest cache directory. 
Document all the things
> Document subscriber client

- CHANGELOG.md
- rele/__init__.py
- Bump version.
- Update changelog
🚀
> Prepare version 0.6.0

- docs/api/settings.rst
Fix ENCODER_PATH docs
Its wrong
> Fix settings docs

- docs/api/middleware.rst
- docs/index.rst
- rele/contrib/django_db_middleware.py
- rele/contrib/logging_middleware.py
- rele/middleware.py
Add documentation for middleware classes.
Docs docs and docs
> Document middleware

- AUTHORS.md
Get my name out of AUTHORS
Don't want to be linked to this
> Remove from Authors

- CHANGELOG.md
- rele/__init__.py
> Bump version to 0.8.0

- README.md
- docs/index.rst
include a what it looks like section
It would be nice when linking to the repo to see what the main project api actually looks like instead of having to navigate to the docs.
> Update readme with a quick "What it looks like" section

- docs/guides/flask.rst
Add some docs on the flask integration
> add some basic docs on flask setup

- CHANGELOG.md
- rele/__init__.py
Update changelog for 0.9.1
Bug fixes
> Release 0.9.1

- docs/api/settings.rst
- rele/client.py
- tests/test_client.py
Configure timeout from .publish()
More granular timeout configuration
Fixes #137
> Configure timeout from .publish()

- CHANGELOG.md
- rele/__init__.py
> Changelog for 0.10.0

- CHANGELOG.md
- rele/__init__.py
- setup.py
Bump version
We have some new stuff to release
> Bump version -- 0.11.0

- CHANGELOG.md
- rele/__init__.py
- rele/config.py
- rele/subscription.py
- tests/subs.py
- tests/test_config.py
Support class based subscribers
We have some services using class based subscriptions, as it removes a lot of boilerplate. 
#161
> Load class based subscribers

- CHANGELOG.md
- rele/__init__.py
- rele/subscription.py
Add docs for class based subscriptions
Now that we support it, we should document it.
#168 #161
> Add docs for class based subscriptions

- CHANGELOG.md
- rele/__init__.py
Update changelog
0.13.0 release
> Update changelog for 0.13.0 release

- docs/guides/basics.rst
- docs/guides/django.rst
- docs/guides/emulator.rst
- docs/guides/flask.rst
- docs/guides/unrecoverable_middleware.rst
- docs/settings.rst
- rele/config.py
- tests/commands/test_runrele.py
- tests/settings.py
- tests/test_config.py
Remove GC_PROJECT_ID from the settings
#178 It was deprecated
#176
> Remove GC_PROJECT_ID

- CHANGELOG.rst
- rele/__init__.py
> Release 1.1.0

- CHANGELOG.rst
- rele/__init__.py
Prepare 1.1.1 release
We have some stuff ready for a minor bump
#200 #199
> Prepare v1.1.1 release

- CHANGELOG.rst
- rele/__init__.py
Prepare release for version `v1.3.0` including:
* GC Project Id & Windows support (#215)
> Release v1.3.0

- AUTHORS.md
- CHANGELOG.rst
- docs/guides/filters.rst
- rele/__init__.py
- rele/subscription.py
Prepare version 1.5.0 and fix sub decorator
To add the new backend filter by functionality
N/A
> Prepare version 1.5.0 and fix sub decorator

- CHANGELOG.rst
- rele/__init__.py
> Prepare version to 1.6.0

- Makefile
- requirements/test.txt
- tests/contrib/test_logging_middleware.py
- tests/contrib/test_verbose_logging_middleware.py
- tests/test_discover.py
- tests/test_publishing.py
* Adds `make lint-fix` for automagically fixing coding style issues. NOTE: `isort .` requires isort v5
* Upgrade isort from v4 to v5
* Apply some minor changes in the imports after upgrading to v5
Improves the Developer eXperience by making more simple compliance with the coding styles rules
> [chore] Linting improvements

- CHANGELOG.rst
- rele/__init__.py
Prepare release of version `1.7.0`
> Prepare release of version `1.7.0`

- rele/__init__.py
> Bump to v1.8.0

- CHANGELOG.rst
- rele/__init__.py
Prepare release of version `1.9.0`
> Prepare release of version `1.9.0`

- rele/__init__.py
Bumped rele to 1.12.0b2
To make available the latest changes on the discovery of the subs
[Related PR](https://github.com/mercadona/rele/pull/257)
> [Changed] Bumped the lib to 1.12.0b2

- rele/__init__.py
Bumped the lib to release 1.12.0
The beta version has been validated for more than a week
[Beta 1 PR](https://github.com/mercadona/rele/pull/255)
[Beta 2 PR](https://github.com/mercadona/rele/pull/257)
> [Changed] Bumped the lib to release 1.12.0

- .github/CODEOWNERS
> Add jonasae as codeowner.

- rele/__init__.py
- rele/client.py
- rele/worker.py
- Version alfa to test rele worker stuck in consumption due a loss of network connectivity.
- Added logs.
- We want to test in a production environment this fix for consumption.
- We added print since logger not working as expected. We will improve this in the release.
- WIP we will add more info to the issue once we test the alfa.
> Fix recover due a loss of network connectivity

- CHANGELOG.rst
- Update change log
Provide a description of what has been implemented.
- For version 1.15.1
Give an explanation of why.
> Update change log

- rele/__init__.py
- rele/worker.py
Restart the main process if we receive any kind of exceptions managed by the Pub/Sub library.
To avoid having dangling threads that avoid the rest of the workers consuming messages.
> Refator check_internet_connections

- rele/__init__.py
Provide a description of what has been implemented.
Have a list of regions available by default to both create and subscribe to Pub/Sub topics
No related Issues
> Enable multiple storage regions by default in PubSub with GC_STORAGE_REGION setting

- CHANGELOG.rst
- rele/__init__.py
Update the Changelog with the new version
To reflect the latest changes
> Update Changelog with new version
